### ISSUE TITLE
Error with PGB cli 6.3: "missing: URL_SCHEME"

### ISSUE THREAD

**Issue by yarontt** [hypery2k/cordova-urlhandler-plugin#7]
Hi,

I'm using Phonegap Build with cli 6.3 for Android and iOS platforms.
I've added the plugin to config.xml:
```
  <plugin name="cordova-plugin-urlhandler" spec="0.7.2" source="npm" >
    <param name="URL_SCHEME" value="zooz" />
  </plugin>
```

I get an error: "missing: URL_SCHEME"
and at the top of the PGB page there's a message "App or plugin contains illegal (or orphaned) symlink".

any ideas?

**Comment by hypery2k** [comment]
Sorry to say but this plugin is not intented to work with PCB

**Comment by yarontt** [comment]
Why not make it work with it? Is it that much work?

**Comment by hypery2k** [comment]
I don't have any experience with phone gap  build and no time to support.

But an PR to this is welcome.
